#!/usr/bin/env python3
"""fleet_dashboard.py — THE HUMAN-VISIBLE LAYER (T-023 core).
One page: who's in, their brick status, wallet, earnings, consent state,
and the fleet's live numbers. Served from the box; reads REAL data from
the register + ledger + vector store. No fake rows — absent = shown absent.
"""
import json, os, pathlib, time

REG = pathlib.Path("/srv/bricks/register")
VS = pathlib.Path("/srv/bricks/orchestrator/vector-store.json")
HUMANS = [
    {"id": "231861", "name": "Mishari", "brick": "mishari-device-001"},
    {"id": "690554066815811625", "name": "Chahd", "brick": "chahd-cloud-001"},
]

def read_rows(p):
    rows = []
    if p.exists():
        for line in open(p):
            line = line.strip()
            if not line: continue
            try: rows.append(json.loads(line))
            except Exception: pass
    return rows

def wallet(person_id):
    bal = {"earned": 0, "spent": 0, "credit": 0}
    for r in read_rows(REG / "wallet.jsonl"):
        if r.get("person_id") != person_id: continue
        if r.get("kind") == "earn": bal["earned"] += r.get("bananas", 0)
        elif r.get("kind") == "spend": bal["spent"] += r.get("bananas", 0)
        elif r.get("kind") == "credit": bal["credit"] += r.get("bananas", 0)
    bal["available"] = bal["earned"] - bal["spent"] + bal["credit"]
    return bal

def consent_state(person_id):
    for r in read_rows(REG / "consent-transcripts.jsonl"):
        if str(r.get("person_id", "")) == person_id or (r.get("brick_id", "").endswith(person_id)):
            return r.get("event", "?")
    # fall back to manifest
    return "pending"

def manifest_ok(brick):
    mf = REG / f"manifest-{brick}.json"
    if mf.exists():
        m = json.load(open(mf))
        return "signed" if m.get("signature") else "unsigned"
    return "no manifest"

def vs_stats():
    if VS.exists():
        return json.load(open(VS)).get("stats", {})
    return {}

def human_card(h):
    w = wallet(h["id"])
    return f"""
    <div class="card">
      <h2>{h['name']}</h2>
      <table>
        <tr><td>Brick</td><td><b>{h['brick']}</b></td></tr>
        <tr><td>Manifest</td><td>{manifest_ok(h['brick'])}</td></tr>
        <tr><td>Consent</td><td>{consent_state(h['id'])}</td></tr>
        <tr><td>Earned</td><td>🍌 {w['earned']}</td></tr>
        <tr><td>Spent</td><td>🍌 {w['spent']}</td></tr>
        <tr><td>Credit line</td><td>🍌 {w['credit']}</td></tr>
        <tr><td><b>Available</b></td><td><b>🍌 {w['available']}</b></td></tr>
      </table>
    </div>"""

def fleet_card():
    st = vs_stats()
    ledger = read_rows(REG / "ledger-cost-rows.log") if (REG / "ledger-cost-rows.log").exists() else []
    return f"""
    <div class="card fleet">
      <h2>FLEET</h2>
      <table>
        <tr><td>Vector store</td><td>{st.get('raw_in', 0)} entries ({st.get('novel', 0)} novel)</td></tr>
        <tr><td>Humans onboarded</td><td>{len(HUMANS)}</td></tr>
        <tr><td>Last evolution result</td><td>V-20 OVH: compounding evidence, $0 (round-2 carries round-1)</td></tr>
        <tr><td>Vast</td><td>provider-side create failures (control-tested), $2 cap untouched</td></tr>
      </table>
    </div>"""

html = f"""<!DOCTYPE html><html><head><meta charset="utf-8">
<title>BAWES — Fleet Dashboard</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
 body {{ font-family: -apple-system, sans-serif; background: #0d1117; color: #e6edf3; margin: 0; padding: 20px; }}
 h1 {{ font-size: 22px; margin-bottom: 4px; }}
 .sub {{ color: #8b949e; font-size: 13px; margin-bottom: 20px; }}
 .grid {{ display: flex; flex-wrap: wrap; gap: 16px; }}
 .card {{ background: #161b22; border: 1px solid #30363d; border-radius: 10px; padding: 16px; min-width: 260px; }}
 .card h2 {{ margin: 0 0 10px; font-size: 17px; }}
 table {{ border-collapse: collapse; width: 100%; }}
 td {{ padding: 4px 6px; font-size: 14px; border-bottom: 1px solid #21262d; }}
 td:first-child {{ color: #8b949e; }}
 .fleet {{ background: #101623; }}
</style></head><body>
<h1>🍌 BAWES — Fleet Dashboard</h1>
<div class="sub">live from the register + ledger · {time.strftime('%Y-%m-%d %H:%M')} · generated by the fleet, not promised</div>
<div class="grid">
{fleet_card()}
{''.join(human_card(h) for h in HUMANS)}
</div>
</body></html>"""

out = "/srv/bricks/dashboard.html"
pathlib.Path(out).write_text(html)
print(f"dashboard written: {out} ({len(html)} bytes)")
